# Generated by Django 5.1.15 on 2026-07-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_active',
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DEACTIVATED', 'Deactivated')], default='WAITING', max_length=20),
        ),
    ]
